Update analog

diff --git a/ubuntu/analog b/ubuntu/analog
--- a/ubuntu/analog
+++ b/ubuntu/analog
@@ -1,177 +1,179 @@
-Version="1.0.1"
+#!/bin/bash
+
+# 变量初始化
+projectName=${PRJECT_NAME-""}
+workDir="$HOME/satea/$projectName"
+dataDir="$HOME/satea/$projectName/data"
+nodename=${analog-""}
+ALL_SATEA_VARS=("projectName")
+
+mkdir -p $dataDir
+cd $workDir
 
 # 定义要检查的包列表
 packages=(
-  docker-ce
-  curl
+    jq
+    curl
+    wget
 )
 
-# 检查并安装每个包
-function installpkg() {
-    for pkg in "${packages[@]}"; do
-    if dpkg-query -W "$pkg" >/dev/null 2>&1; then
-        echo "$pkg installed,skip"
-    else
-        echo "install  $pkg..."
-        sudo apt update
-        sudo apt install -y "$pkg"
-    fi
-done
-}
-
-
-
-##定义脚本变量
-
-#举例： 这个脚本需要依赖  test01 test02 username passwd
-
-#  第一步: 在ALL_SATEA_VARS定义变量 用逗号隔开,方便手动模式下Manual函数解析需要的变量
-
-ALL_SATEA_VARS="username"
-
-#  第二步: 创建变量 并设置站位符号, 方便自动模式下系统替换变量
-
-username={{SATEA_VARS_username}}
-
-
-##显示需要接收的变量
-function VadVars(){
-     echo "$ALL_SATEA_VARS"
+function checkVars() {
+    # 循环遍历数组
+    for var_name in "${ALL_SATEA_VARS[@]}"; do
+        # 动态读取变量的值
+        value=$(eval echo \$$var_name)
+        if [ -z "$value" ]; then
+            # 如果为空，输出错误提示
+            echo "Error: Variable $var_name is not set!"
+            exit 1
+        else
+            # 如果不为空，输出变量名及其值
+            echo "Variable $var_name value is $value"
+        fi
+    done
 }
 
 #手动模式下 解析并填入变量的函数
-function Manual() {
-   >.env.sh
-   chmod +x .env.sh
-   for i in `echo $ALL_SATEA_VARS | tr ',' '\n' `;do
+function readVariables() {
+    >.env.sh
+    chmod +x .env.sh
+    for var_name in "${ALL_SATEA_VARS[@]}"; do
+        read -p "Please input $var_name: " read_value
+        echo "$var_name=$read_value" >>.env.sh
+    done
+}
 
-   i_split=`echo $i |tr -d "{" | tr -d "}"`
+# 检查并安装每个包
+function checkPackages() {
+    echo "check packages ..."
+    for pkg in "${packages[@]}"; do
+        if dpkg-query -W "$pkg" >/dev/null 2>&1; then
+            echo "$pkg installed,skip"
+        else
+            echo "install  $pkg..."
+            sudo apt update
+            sudo apt install -y "$pkg"
+        fi
+    done
+}
 
-   read  -p "$i_split ="  i_split_vars
+function install() {
+docker run -d \
+--name analog \
+-p 30333:30333 \
+-p 9944:9944 \
+-v $workDir:/data analoglabs/timenode-test:latest \
+--base-path /data \
+--name $nodename\
+--validator --unsafe-rpc-external --rpc-methods=unsafe
+}
 
-   echo "$i_split=$i_split_vars" >>.env.sh
+function start() {
+    echo "start ..."
+    docker start analog
+}
 
-  done
+function stop() {
+    echo "stop ..."
+    docker stop analog
+}
+
+function upgrade() {
+    echo "upgrade ..."
+    docker stop analog
+    docker rm -f analog
+    docker rmi analoglabs/timenode-test:latest
+docker run -d \
+--name analog \
+-p 30333:30333 \
+-p 9944:9944 \
+-v $workDir:/data analoglabs/timenode-test:latest \
+--base-path /data \
+--name $nodename\
+--validator --unsafe-rpc-external --rpc-methods=unsafe
 }
 
 
 
-function install(){
-  echo "install steps"
-  docker run -d --network="host" --name analog -v /var/lib/analog:/data analoglabs/timechain \
-  --base-path /data \
-  --rpc-external \
-  --unsafe-rpc-external \
-  --rpc-cors all \
-  --name=$username \
-  --rpc-methods Unsafe
-  sleep 2
-    curl http://127.0.0.1:9944 -H "Content-Type:application/json;charset=utf-8" -d   '{
-    "jsonrpc":"2.0",
-    "id":1,
-    "method":"author_rotateKeys",
-    "params": []
-  }' >analog-key.txt
+function clean() {
+    echo "clean ...."
+    docker stop analog
+    docker rm -f analog
+    docker rmi analoglabs/timenode-test:latest
+    rm -rf $workDir
 }
-function logs(){
-  docker logs analog -f --tail 20
-}
-function clean(){
-  docker stop analog
-  docker rm -f analog
-}
-function restart(){
-  docker restart analog
-}
-function show_key(){
-  cat analog-key.txt
+
+function logs() {
+    echo "logs ...."
+    docker logs analog
 }
 
 function About() {
-echo '   _____    ___       ______   ______   ___
-  / ___/   /   |     /_  __/  / ____/  /   |
-  \__ \   / /| |      / /    / __/    / /| |
- ___/ /  / ___ |     / /    / /___   / ___ |
-/____/  /_/  |_|    /_/    /_____/  /_/  |_|'
+    echo '   _____    ___     ______   ______   ___
+  / ___/   /   |   /_  __/  / ____/  /   |
+  \__ \   / /| |    / /    / __/    / /| |
+ ___/ /  / ___ |   / /    / /___   / ___ |
+/____/  /_/  |_|  /_/    /_____/  /_/  |_|'
 
-echo
-echo -e "\xF0\x9F\x9A\x80 Satea Node Installer
+    echo
+    echo -e "\xF0\x9F\x9A\x80 Satea Node Installer
 Website: https://www.satea.io/
 Twitter: https://x.com/SateaLabs
 Discord: https://discord.com/invite/satea
 Gitbook: https://satea.gitbook.io/satea
-Version: $Version
+Version: V1.0.0
 Introduction: Satea is a DePINFI aggregator dedicated to breaking down the traditional barriers that limits access to computing resources.  "
-echo""
+    echo""
 }
 
-
-
-
-
 case $1 in
-
+check-packages)
+    checkPackages
+    ;;
 install)
-
-  if [ "$2" = "--auto" ]
-  then
-     echo "-> Automatic mode, please ensure that ALL SATEA_VARS(`VadVars`) have been replaced !"
-          sleep 3
-
-     #这里使用自动模式下的 安装 函数
-     install
-
+    if [ "$2" = "--auto" ]; then
+        #这里使用自动模式下的 安装 函数
+        install
     else
-      echo "Unrecognized variable(`VadVars`) being replaced, manual mode"
-
-      #手动模式 使用Manual 获取用户输入的变量
-
-      Manual      #获取用户输入的变量
-      . .env.sh   #导入变量
-
-      #其他安装函数
-      install
-
-
+        #手动模式 使用Manual 获取用户输入的变量
+        readVariables #获取用户输入的变量
+        . .env.sh     #导入变量
+        #其他安装函数
+        install
     fi
-  ;;
-
-
-vars)
- #展示变量
-VadVars
-
-  ;;
-
+    ;;
+start)
+    #创建启动节点的函数
+    start
+    ;;
+stop)
+    #创建停止节点的函数
+    stop
+    ;;
+upgrade)
+    #创建升级节点的函数
+    upgrade
+    ;;
 clean)
-clean
-
-  ;;
-
-restart)
-restart
-
-  ;;
-
+    #创建清除节点的函数
+    clean
+    ;;
 logs)
-logs
-
-  ;;
-
-show_key)
-show_key
-  ;;
-
+    #打印节点信息
+    logs
+    ;;
 
 **)
 
- #定义帮助信息 例子
- About
-  echo "Flag:
-  install              Install analog with manual mode,  If carrying the --auto parameter, start Automatic mode
-  init                 Install Dependent packages
-  show_key             show your keys
-  logs                 Show the logs of the analog service
-  clean                Remove the analog from your server"
-  ;;
+    #定义帮助信息 例子
+    About
+    echo "Flag:
+  check-packages       Check basic installation package
+  install              Install $projectName environment
+  start                Start the $projectName service
+  stop                 Stop the $projectName service
+  upgrade              Upgrade an existing installation of $projectName
+  clean                Remove the $projectName from your service, remove data!!! 
+  logs                 Show the logs of the $projectName service"
+    ;;
 esac
