Update fuel

diff --git a/ubuntu/fuel b/ubuntu/fuel
--- a/ubuntu/fuel
+++ b/ubuntu/fuel
@@ -1,107 +1,89 @@
-Version="1.0.1"
+#!/bin/bash
+
+# 变量初始化
+projectName=${PRJECT_NAME-"fuel"}
+workDir="$HOME/satea/$projectName"
+dataDir="$HOME/satea/$projectName/data"
+moniker=${MONIKER-""}
+ALL_SATEA_VARS=("projectName,moniker")
+
+mkdir -p $dataDir
+cd $workDir
 
 # 定义要检查的包列表
 packages=(
-    ca-certificates \
-    curl \
-    gnupg \
-    expect \
-    screen \
-    jq \
-    wget \
-    unzip \
-    zip \
-    git \
-    net-tools
+    jq
+    curl
+    wget
 )
 
-# 检查并安装每个包
-function init() {
-    for pkg in "${packages[@]}"; do
-    if dpkg-query -W "$pkg" >/dev/null 2>&1; then
-        echo "$pkg installed,skip"
-    else
-        echo "install  $pkg..."
-        sudo apt update
-        sudo apt install -y "$pkg"
-    fi
-done
-    if command -v go >/dev/null 2>&1; then
-    echo "go 已安装，跳过安装步骤。"
-else
-    echo "下载并安装 Go..."
-    wget -c https://golang.org/dl/go1.22.4.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
-    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
-
-fi
-    if command -v pm2 &> /dev/null
-then
-    echo "pm2 已安装，跳过安装步骤"
-else
-    echo "pm2 未安装，开始安装"
-    apt update
-    apt install npm -y
-    npm install -g n
-    n latest
-    hash -r
-
-    npm install pm2@latest -g
-fi
-}
-
-ALL_SATEA_VARS="name,rpckey"
-name={{SATEA_VARS_name}}
-rpckey={{SATEA_VARS_rpckey}}
-
-
-
-
-##显示需要接收的变量
-function VadVars(){
-     echo "$ALL_SATEA_VARS"
+function checkVars() {
+    # 循环遍历数组
+    for var_name in "${ALL_SATEA_VARS[@]}"; do
+        # 动态读取变量的值
+        value=$(eval echo \$$var_name)
+        if [ -z "$value" ]; then
+            # 如果为空，输出错误提示
+            echo "Error: Variable $var_name is not set!"
+            exit 1
+        else
+            # 如果不为空，输出变量名及其值
+            echo "Variable $var_name value is $value"
+        fi
+    done
 }
 
 #手动模式下 解析并填入变量的函数
-function Manual() {
-   >.env.sh
-   chmod +x .env.sh
-   for i in `echo $ALL_SATEA_VARS | tr ',' '\n' `;do
-
-   i_split=`echo $i |tr -d "{" | tr -d "}"`
-
-   read  -p "$i_split ="  i_split_vars
-
-   echo "$i_split=$i_split_vars" >>.env.sh
-
-  done
+function readVariables() {
+    >.env.sh
+    chmod +x .env.sh
+    for var_name in "${ALL_SATEA_VARS[@]}"; do
+        read -p "Please input $var_name: " read_value
+        echo "$var_name=$read_value" >>.env.sh
+    done
 }
 
-function install(){
-PATH=$PATH:/usr/local/go/bin
-# 验证安装后的 Go 版本
-echo "当前 Go 版本："
-go version
-mkdir fuel && cd fuel
-curl https://install.fuel.network | sh
-echo 'export PATH="$HOME/.fuelup/bin:$PATH"' >>.bashrc
+# 检查并安装每个包
+function checkPackages() {
+    echo "check packages ..."
+    for pkg in "${packages[@]}"; do
+        if dpkg-query -W "$pkg" >/dev/null 2>&1; then
+            echo "$pkg installed,skip"
+        else
+            echo "install  $pkg..."
+            sudo apt update
+            sudo apt install -y "$pkg"
+        fi
+    done
+}
+
+function install() {
+/usr/bin/expect <<EOF
+spawn sh -c {curl https://install.fuel.network | sh}
+expect {
+    "Would you like fuelup-init to modify your PATH variable for you? (N/y)" {
+        send "y\r"
+        exp_continue
+    }
+    eof
+}
+EOF
 . $HOME/.bashrc
 export PATH="$HOME/.fuelup/bin:$PATH" && fuel-core -V
-if [ $? -eq 0 ]
-then
 git clone https://github.com/FuelLabs/chain-configuration.git
-echo $rpckey $name
+echo $rpckey $moniker
 rpc="https://sepolia.infura.io/v3/$rpckey"
 echo $rpc
-fuel-core-keygen new --key-type peering 2>&1 |tee $HOME/fuel/key
-keypair=$(cat $HOME/fuel/key |awk -F':' '{print $3}' |awk -F'"' '{print $2}')
-cat >$HOME/fuel/fuel.sh<<EOF
+fuel-core-keygen new --key-type peering 2>&1 |tee $workDir/fuel_key
+keypair=$(cat $workDir/fuel_key |awk -F':' '{print $3}' |awk -F'"' '{print $2}')
+cat >$workDir/fuel.sh<<EOF
 fuel-core run \
---service-name="$name" \
+--service-name="$moniker" \
 --keypair $keypair \
 --relayer $rpc \
 --ip=0.0.0.0 --port=4000 --peering-port=30333 \
---db-path=~/.fuel-sepolia-testnet \
---snapshot $HOME/chain-configuration/ignition/ \
+--db-path=$workDir/.fuel-sepolia-testnet \
+--snapshot $workDir/chain-configuration/ignition/ \
 --utxo-validation --poa-instant false --enable-p2p \
 --reserved-nodes /dns4/p2p-testnet.fuel.network/tcp/30333/p2p/16Uiu2HAmDxoChB7AheKNvCVpD4PHJwuDGn8rifMBEHmEynGHvHrf \
 --sync-header-batch-size 100 \
@@ -111,114 +93,131 @@ fuel-core run \
 --relayer-log-page-size=500 \
 --sync-block-stream-buffer-size 30
 EOF
-pm2 start $HOME/fuel/fuel.sh --name fuel-core && pm2 save
-else
-	echo "install error"
-fi
+pm2 start $workDir/fuel.sh --name fuel-core && pm2 save
 }
 
+function start() {
+    echo "start ..."
+    checkVars
+    pm2 start fuel-core
+}
 
-function log(){
+function stop() {
+    echo "stop ..."
+    pm2 stop fuel-core
+}
+
+function upgrade() {
+    echo "upgrade ..."
+    pm2 stop fuel-core
+    cd $workDir
+    /usr/bin/expect <<EOF
+    spawn sh -c {curl https://install.fuel.network | sh}
+    expect {
+    "Would you like fuelup-init to modify your PATH variable for you? (N/y)" {
+        send "y\r"
+        exp_continue
+    }
+    eof
+}
+EOF
+fuel-core -V
+pm2 restart fuel-core
+}
+
+function check() {
+    echo "check ..."
+    pm2 list 
+}
+function stop(){
+    pm2 stop fuel-core
+}
+funciton start(){
+    pm2 start fuel-core
+}
+function clean() {
+    echo "clean ...."
+    pm2 stop fuel-core && pm2 delete fuel-core && pm2 save
+    rm -rf $workDir
+}
+function logs() {
+    echo "logs ...."
     pm2 logs fuel-core
 }
-
 function version(){
     $HOME/.fuelup/bin/fuel-core -V
 }
 
-function restart(){
-    pm2 restart fuel-core
-}
-
-function key(){
-cat $HOME/fuel/key
-}
-
-function clean(){
-pm2 stop fuel-core && pm2 delete fuel-core && pm2 save
-sudo rm -rf .fuel*
-sudo rm -rf fule
-}
 
 function About() {
-echo '   _____    ___     ______   ______   ___
+    echo '   _____    ___     ______   ______   ___
   / ___/   /   |   /_  __/  / ____/  /   |
   \__ \   / /| |    / /    / __/    / /| |
  ___/ /  / ___ |   / /    / /___   / ___ |
 /____/  /_/  |_|  /_/    /_____/  /_/  |_|'
 
-echo
-echo -e "\xF0\x9F\x9A\x80 Satea Node Installer
+    echo
+    echo -e "\xF0\x9F\x9A\x80 Satea Node Installer
 Website: https://www.satea.io/
 Twitter: https://x.com/SateaLabs
 Discord: https://discord.com/invite/satea
 Gitbook: https://satea.gitbook.io/satea
-Version: $Version
+Version: V1.0.0
 Introduction: Satea is a DePINFI aggregator dedicated to breaking down the traditional barriers that limits access to computing resources.  "
-echo""
+    echo""
 }
 
-
-
-
-
 case $1 in
-
+check-packages)
+    checkPackages
+    ;;
 install)
-
-  if [ "$2" = "--auto" ]
-  then
-     echo "-> Automatic mode, please ensure that ALL SATEA_VARS(`VadVars`) have been replaced !"
-          sleep 3
-
-     #这里使用自动模式下的 安装 函数
-     install
-
+    if [ "$2" = "--auto" ]; then
+        #这里使用自动模式下的 安装 函数
+        install
     else
-      echo "Unrecognized variable(`VadVars`) being replaced, manual mode"
-
-      #手动模式 使用Manual 获取用户输入的变量
-
-      Manual      #获取用户输入的变量
-      . .env.sh   #导入变量
-
-      #其他安装函数
-      install
+        #手动模式 使用Manual 获取用户输入的变量
+        readVariables #获取用户输入的变量
+        . .env.sh     #导入变量
+        #其他安装函数
+        install
     fi
-  ;;
-init)
-init
-  ;;
-vars)
-VadVars
-  ;;
+    ;;
+start)
+    start
+    ;;
+stop)
+    stop
+    ;;
+upgrade)
+    upgrade
+    ;;
+check)
+    check
+    ;;
 clean)
-clean
-  ;;
-restart)
-restart
-  ;;
-key)
-key
- ;;
-log)
-log
-;;
+    clean
+    ;;
+logs)
+    logs
+    ;;
 version)
-version
-;;
+    version
+    ;;
 
 **)
 
- #定义帮助信息 例子
- About
-  echo "Flag:
-  install         Install fuel with manual mode,  If carrying the --auto parameter, start Automatic mode
-  init            Install Dependent packages
-  restart         restart the service         
-  key             show your key
-  version         show your version
-  log             show your logs
-  clean           Remove the fuel from your server"
-  ;;
+    #定义帮助信息 例子
+    About
+    echo "Flag:
+  check-packages       Check basic installation package
+  install              Install $projectName environment
+  start                Start the $projectName service
+  stop                 Stop the $projectName service
+  upgrade              Upgrade an existing installation of $projectName
+  check                Check $projectName service status
+  clean                Remove the $projectName from your service, remove data!!! 
+  logs                 Show the logs of the $projectName service
+  version              show the version of the $projectName service "
+    ;;
 esac
